# Generated by Django 4.0.1 on 2022-02-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_computrabajo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleos_categoria',
            name='actitudes',
        ),
    ]
