# Generated by Django 4.0.1 on 2022-02-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_computrabajo', '0002_remove_empleos_categoria_actitudes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleos_categoria',
            name='detalles_autor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleos_categoria',
            name='funciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
