# Generated by Django 4.0.1 on 2022-02-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_computrabajo', '0003_alter_empleos_categoria_detalles_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleos_cargo_profesional',
            name='actitudes',
        ),
        migrations.RemoveField(
            model_name='empleos_ciudad',
            name='actitudes',
        ),
        migrations.RemoveField(
            model_name='empleos_estado_federal',
            name='actitudes',
        ),
        migrations.AlterField(
            model_name='empleos_cargo_profesional',
            name='detalles_autor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleos_cargo_profesional',
            name='experiencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleos_cargo_profesional',
            name='funciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleos_ciudad',
            name='detalles_autor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleos_ciudad',
            name='funciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleos_estado_federal',
            name='detalles_autor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleos_estado_federal',
            name='funciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleos_localizacion',
            name='experiencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleos_localizacion',
            name='funciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleos_sueldo',
            name='media_salarial',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
