# Generated by Django 4.0.1 on 2022-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_computrabajo', '0004_remove_empleos_cargo_profesional_actitudes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleos_categoria',
            name='ofertas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleos_estado_federal',
            name='ofertas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresas_industria',
            name='ofertas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
