# Generated by Django 4.0.1 on 2022-02-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_computrabajo', '0005_alter_empleos_categoria_ofertas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleos_ciudad',
            name='titulo',
        ),
    ]
