# Generated by Django 4.0.1 on 2022-03-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_computrabajo', '0008_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='servicios',
            name='subtitulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
