# Generated by Django 4.0.1 on 2022-03-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_computrabajo', '0009_orienta_servicios_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='orienta',
            name='subtitulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
