# Generated by Django 4.0.3 on 2022-04-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_computrabajo', '0011_comentarios_delete_empleos_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'verbose_name': 'mensaje', 'verbose_name_plural': 'mensajes'},
        ),
        migrations.AddField(
            model_name='empleos_cargo_profesional',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
